INSERT INTO Genre VALUES(1, 'Комедия');
INSERT INTO Genre VALUES(2, 'Драма');
INSERT INTO Genre VALUES(3, 'Мультфильм');
INSERT INTO Genre VALUES(4, 'Триллер');
INSERT INTO Genre VALUES(5, 'Документальный');
INSERT INTO Genre VALUES(6, 'Боевик');

INSERT INTO MPA VALUES(1, 'G');
INSERT INTO MPA VALUES(2, 'PG');
INSERT INTO MPA VALUES(3, 'PG-13');
INSERT INTO MPA VALUES(4, 'R');
INSERT INTO MPA VALUES(5, 'NC-17');