INSERT INTO Genre VALUES(1, '1');
INSERT INTO Genre VALUES(2, '2');
INSERT INTO Genre VALUES(3, '3');
INSERT INTO Genre VALUES(4, '4');
INSERT INTO Genre VALUES(5, '5');
INSERT INTO Genre VALUES(6, '6');

INSERT INTO MPA VALUES(1, 'G');
INSERT INTO MPA VALUES(2, 'PG');
INSERT INTO MPA VALUES(3, 'PG-13');
INSERT INTO MPA VALUES(4, 'R');
INSERT INTO MPA VALUES(5, 'NC-17');